Repository ase-lab-space/ase-lab, pull requests merged in 2022-07, with the labels that each got.

#20 Activitiesページのモバイル対応
  frontend/src/components/ActivitiesPage/AseTalks/AseTalksView.vue
  frontend/src/components/ActivitiesPage/HeadingView.vue
  frontend/src/components/ActivitiesPage/Seminar/SeminarsView.vue
Labels: 機能開発

#25 Update metadata
  src/models/meta.ts
Labels: メタ情報

#27 info-update
  src/models/seminars.ts
Labels: ゼミ関連

#24 articlesページのMobile対応
  src/pages/ArticlesPage.vue
Labels: 機能開発

#28 Add .dockerignore
  .dockerignore
  Dockerfile
Labels: バグ修正
