Repository ase-lab-space/ase-lab, pull requests merged in 2022-10, with the labels that each got.

#30 Update seminars.ts
  src/models/seminars.ts
Labels: ゼミ関連

#48 記事追加
  src/models/articles.ts
Labels: 記事関連

#49 Update meta info
  src/models/meta.ts
Labels: メタ情報

#50 Remove 流体力学ゼミ
  src/models/seminars.ts
Labels: ゼミ関連
