Repository ase-lab-space/ase-lab, pull requests merged in 2022-08, with the labels that each got.

#29 Fix 流体力学's seminar image url
  src/models/seminars.ts
Labels: ゼミ関連

#38 コンマとピリオドを句読点に変更した
  src/models/seminars.ts
Labels: ゼミ関連

#40 人数の変更
  src/models/meta.ts
Labels: メタ情報

#39 Contactフォームが送信されたときにSlackに通知する
  src/components/ContactPage/ContactForm.vue
  src/repositories/base_repository.ts
  src/repositories/emailjs_repository.ts
  src/repositories/slack_repository.ts
Labels: 機能改善
