Repository ase-lab-space/ase-lab, pull requests merged in 2022-05, with the labels that each got.

#1 ゼミ修正のためのテンプレート追加
  .github/PULL_REQUEST_TEMPLATE/SEMINAR.md
Labels: documentation

#2 Fix pr template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/SEMINAR.md
Labels: documentation

#3 第二回画像処理ゼミにdescriptionを追加
  frontend/src/models/seminars.ts
Labels: ゼミ関連

#4 OGPタグを追記
  frontend/public/img/home.webp
  frontend/src/index.template.html
Labels: enhancement

#5 README.mdを詳細に記述
  README.md
Labels: documentation

#7 Update about.ts
  frontend/src/models/about.ts
Labels: enhancement

#8 GitHubアイコンを追加
  frontend/src/components/MainLayout/FooterView.vue
Labels: 機能開発

#9 ContactページのMobile対応
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/mq.scss
  frontend/src/components/Common/PageTitle.vue
  frontend/src/components/Common/Transition/SlideIn.vue
  frontend/src/components/ContactPage/ContactForm.vue
  frontend/src/components/MainLayout/HambergerIcon.vue
  frontend/src/components/MainLayout/LinkOverlay.vue
  frontend/src/css/app.scss
  frontend/src/layouts/MainLayout.vue
Labels: 機能開発

#11 開発環境構築手順のREADME.mdを追記
  README.md
Labels: documentation

#10 IndexページのMobile対応
  frontend/src/components/Common/Button/DoubleLineLink.vue
  frontend/src/components/Common/Button/SingleLineLink.vue
  frontend/src/components/IndexPage/AboutView.vue
  frontend/src/components/IndexPage/ArticlesView.vue
  frontend/src/components/IndexPage/LargeGlobe.vue
  frontend/src/components/IndexPage/MainView.vue
  frontend/src/components/IndexPage/MapView.vue
  frontend/src/components/IndexPage/SeminarsView.vue
  frontend/src/components/MainLayout/FooterView.vue
  frontend/src/css/app.scss
  frontend/src/layouts/MainLayout.vue
  frontend/src/pages/IndexPage.vue
Labels: 機能開発

#13 参加人数を70人に更新
  frontend/src/models/meta.ts
Labels: メタ情報

#15 参加人数を74人に更新
  frontend/src/models/meta.ts
Labels: メタ情報
