Repository ase-lab-space/ase-lab, pull requests merged in 2022-11, with the labels that each got.

#52 Fix status badge positions
  src/components/ActivitiesPage/Seminar/SeminarCard.vue
Labels: バグ修正

#56 Add new article
  src/models/articles.ts
Labels: 記事関連

#57 Bump loader-utils
  yarn.lock
Labels: 機能改善

#55 Translate ContactPage
  src/boot/i18n.ts
  src/components/ContactPage/ContactForm.vue
  src/i18n/en-US/index.ts
  src/i18n/ja-JP/index.ts
  src/pages/ContactPage.vue
Labels: 機能開発

#60 Translate ActivitiesPage
  public/img/ase-talk.webp
  public/img/seminar-guide-book-thumbnail-en.webp
  public/img/seminar-guide-book-thumbnail-ja.webp
  public/pdf/ASE_Seminar_Guidebook.pdf
  src/boot/i18n.ts
  src/components/ActivitiesPage/AseTalk/AseTalkView.vue
  src/components/ActivitiesPage/AseTalks/AseTalksView.vue
  src/components/ActivitiesPage/Seminar/SeminarCard.vue
  src/components/ActivitiesPage/Seminar/SeminarsView.vue
  src/components/Common/Button/LocaleButton.vue
  src/components/IndexPage/SeminarsView.vue
  src/i18n/en-US/index.ts
  src/i18n/en-US/seminars.ts
  src/i18n/index.ts
  src/i18n/ja-JP/index.ts
  src/i18n/ja-JP/seminars.ts
  src/layouts/MainLayout.vue
  src/models/seminars.ts
  src/pages/ActivitiesPage.vue
  src/router/index.ts
Labels: 機能開発

#61 Fix articles' sort to be descending
  src/components/IndexPage/ArticlesView.vue
  src/pages/ArticlesPage.vue
Labels: 機能改善

#59 Translate ArticlesPage
  src/i18n/en-US/articles.ts
  src/i18n/en-US/index.ts
  src/i18n/ja-JP/articles.ts
  src/i18n/ja-JP/index.ts
  src/models/articles.ts
  src/pages/ArticlesPage.vue
Labels: 機能開発

#62 Add a new article
  src/models/articles.ts
Labels: 記事関連

#63 Update packages / Run linters in CI
  .eslintrc.js
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yml
  .github/workflows/s3_deploy.yml
  .gitignore
  .node-version
  .postcssrc.js
  .vscode/settings.json
  .yarn/releases/yarn-3.3.0.cjs
  .yarnrc.yml
  README.md
  babel.config.js
  package.json
  src/App.vue
  src/components/AboutPage/MapSection.vue
  src/components/ActivitiesPage/AseTalks/AseTalksView.vue
  src/components/ActivitiesPage/HeadingView.vue
  src/components/ActivitiesPage/Seminar/SeminarsView.vue
  src/components/Common/Button/BorderButton.vue
  src/components/Common/PageTitle.vue
  src/components/Common/Transition/SlideIn.vue
  src/components/ContactPage/ContactForm.vue
  src/components/IndexPage/AboutView.vue
  src/components/IndexPage/ArticlesView.vue
  src/components/IndexPage/LandingOverlay.vue
  src/components/IndexPage/NewsView.vue
  src/components/IndexPage/Seminar/SeminarCard.vue
  src/components/MainLayout/HambergerIcon.vue
  src/components/MainLayout/LinkOverlay.vue
  src/i18n/en-US/index.ts
  src/i18n/index.ts
  src/layouts/MainLayout.vue
  src/pages/AboutPage.vue
  src/stores/index.ts
  src/stores/store-flag.d.ts
  tsconfig.json
  yarn.lock
Labels: 機能改善
