Repository ase-lab-space/ase-lab, pull requests merged in 2023-06, with the labels that each got.

#99 S3へのデプロイをやめて、vercelに統一する
  .github/workflows/s3_deploy.yml
  vercel.json
Labels: 機能改善

#100 change the number
  src/models/meta.ts
Labels: メタ情報

#102 update seminar status
  src/models/seminars.ts
Labels: ゼミ関連
