Repository ase-lab-space/ase-lab, pull requests merged in 2023-12, with the labels that each got.

#142 articlest.sのnote記事のtitle変更
  src/i18n/ja-JP/articles.ts
  src/models/articles.ts
Labels: 記事関連

#143 人数の更新
  src/models/meta.ts
Labels: メタ情報

#144 未実施の昔のゼミの削除
  src/models/seminars.ts
Labels: ゼミ関連

#145 note記事を追加
  src/models/articles.ts
  src/models/news.ts
Labels: 記事関連
