Repository ase-lab-space/ase-lab, pull requests merged in 2023-01, with the labels that each got.

#68 Add new seminars
  src/models/seminars.ts
Labels: ゼミ関連

#66 Translate IndexPage
  src/components/IndexPage/AboutView.vue
  src/components/IndexPage/ArticlesView.vue
  src/components/IndexPage/MainView.vue
  src/components/IndexPage/MapView.vue
  src/components/IndexPage/NewsView.vue
  src/components/IndexPage/SeminarsView.vue
  src/i18n/en-US/index.ts
  src/i18n/en-US/news.ts
  src/i18n/ja-JP/index.ts
  src/i18n/ja-JP/news.ts
  src/models/news.ts
  src/pages/IndexPage.vue
Labels: 機能開発

#71 I18n resolve conflicts
  src/models/articles.ts
  src/models/seminars.ts
  src/repositories/slack_repository.ts
Labels: 機能開発

#72 Swap yasuda's article thumbnail
  src/models/articles.ts
Labels: 記事関連

#74 Fix CVE-2022-46175
  yarn.lock
Labels: 機能改善

#76 Improve CTA button design
  public/img/home.webp
  src/components/Common/Button/BorderButton.vue
  src/components/IndexPage/MainView.vue
  src/components/IndexPage/MapView.vue
  src/pages/IndexPage.vue
Labels: 機能改善

#78 update meta.ts
  src/models/meta.ts
Labels: メタ情報

#77 change notation
  src/i18n/en-US/seminars.ts
  src/i18n/ja-JP/seminars.ts
Labels: ゼミ関連
