Repository ase-lab-space/ase-lab, pull requests merged in 2024-03, with the labels that each got.

#159 20240226 seminers english ver
  src/i18n/en-US/seminars.ts
  src/i18n/ja-JP/seminars.ts
  src/models/seminars.ts
Labels: ゼミ関連

#160 20240311 meta update
  src/i18n/en-US/articles.ts
  src/i18n/en-US/seminars.ts
  src/i18n/ja-JP/articles.ts
  src/i18n/ja-JP/seminars.ts
  src/models/articles.ts
  src/models/meta.ts
  src/models/seminars.ts
Labels: メタ情報

#162 Add new article
  src/i18n/en-US/articles.ts
  src/i18n/en-US/news.ts
  src/i18n/ja-JP/articles.ts
  src/i18n/ja-JP/news.ts
  src/models/articles.ts
  src/models/news.ts
Labels: 記事関連

#163 Update seminars
  public/img/seminars/automatic-operation.webp
  public/img/seminars/cosmological-fluid.webp
  public/img/seminars/misson-design.webp
  public/img/seminars/space-business.webp
  src/components/IndexPage/SeminarsView.vue
  src/i18n/en-US/seminars.ts
  src/i18n/ja-JP/seminars.ts
  src/models/seminars.ts
Labels: ゼミ関連

#166 バグ修正
  src/i18n/en-US/seminars.ts
  src/i18n/ja-JP/seminars.ts
  src/models/seminars.ts
Labels: バグ修正
